version: "3.7"
services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./www:/var/www
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
      - ./docker-compose/nginx/logs:/var/log/nginx
      - ./docker-compose/nginx/certs:/etc/nginx/certs/

  php:
    build:
      context: ./docker-compose/php-7.4/
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    links:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      # MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: lex
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_USER: ${DB_USERNAME}
      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/db:/var/lib/mysql
